import { useEffect, useState, lazy, Suspense } from 'react';
import { ArrowLeft, Download, FileAudio, Printer } from 'lucide-react';
import type { AnalyzedAudio } from '../../services/audio';
import { renderSpectrogramPng } from '../../services/audio/spectrogram';
import { calculateReview, type ReviewRecord } from '../../services/review';
import { downloadFile, jsonSafe } from '../../services/library';
import type { LocalModel } from '../../services/learning/types';
import AudioPlayer from '../AudioPlayer';
import Metrics from './Metrics';
import ReviewPanel from './ReviewPanel';
const ModelAdvice = lazy(() => import('./ModelAdvice'));

interface Props { record: ReviewRecord; analyzed: AnalyzedAudio | null; audioUrl: string; records: ReviewRecord[]; model: LocalModel | null; onChange: (patch: Partial<ReviewRecord>) => void; onBack: () => void; referenceUrl: string; onReference: (id: string) => void; referenceId: string }
export default function AnalysisView({ record, analyzed, audioUrl, records, model, onChange, onBack, referenceUrl, onReference, referenceId }: Props) {
  const [spectrum, setSpectrum] = useState('');
  const [tab, setTab] = useState<'wave' | 'spectrum'>('wave');
  const [advice, setAdvice] = useState(false);
  useEffect(() => { setSpectrum(''); setTab('wave'); setAdvice(false); }, [record.id]);
  useEffect(() => { if (tab !== 'spectrum' || !analyzed || spectrum) return; const frame = requestAnimationFrame(() => { const image = renderSpectrogramPng(analyzed.channels, analyzed.sampleRate, { width: 1100, height: 340, fftSize: 2048 }); setSpectrum(`data:image/png;base64,${image.base64}`); }); return () => cancelAnimationFrame(frame); }, [tab, analyzed, spectrum]);
  const reference = records.find(r => r.id === referenceId);
  return <div className="analysis-view">
    <div className="file-heading"><div><button className="text-button back-button" onClick={onBack}><ArrowLeft size={14} /> Biblioteca</button><h2><FileAudio size={25} />{record.name}</h2><p>{record.origin === 'synthetic' ? 'DEMO SINTÉTICA' : 'MUESTRA REAL'} <span>·</span> {record.features.format.sampleRate.toLocaleString('es')} Hz <span>·</span> {record.features.format.bitDepth || '?'} bit <span>·</span> {record.features.format.channels} canales <span>·</span> {record.features.format.duration.toFixed(1)} s</p></div><div className="toolbar"><button className="button secondary" onClick={() => downloadFile(JSON.stringify({ review: record, score: calculateReview(record) }, jsonSafe, 2), `${record.name}.informe.json`)}><Download size={15} /> Informe JSON</button><button className="icon-button" aria-label="Imprimir o guardar informe como PDF" onClick={() => window.print()}><Printer size={18} /></button></div></div>
    <Metrics features={record.features} />
    <section className="panel signal-panel"><div className="panel-heading"><div><span className="eyebrow">EXPLORADOR DE SEÑAL</span><h3>Escucha dónde ocurre.</h3></div><div className="segmented" aria-label="Vista de audio"><button aria-pressed={tab === 'wave'} className={tab === 'wave' ? 'selected' : ''} onClick={() => setTab('wave')}>Forma de onda</button><button disabled={!analyzed} aria-pressed={tab === 'spectrum'} className={tab === 'spectrum' ? 'selected' : ''} onClick={() => setTab('spectrum')}>Espectrograma</button></div></div>
      {tab === 'spectrum' && <div className="spectrogram">{spectrum ? <img src={spectrum} alt="Espectrograma del audio: tiempo horizontal, frecuencia vertical y nivel representado por color." /> : <p>Generando espectrograma local…</p>}</div>}
      {audioUrl ? <AudioPlayer src={audioUrl} features={record.features} /> : <div className="empty-audio">Este registro contiene métricas y etiquetas. Vuelve a subir el audio original para escucharlo; se reconocerá por su huella.</div>}
      {record.features.analysis.warnings.length > 0 && <details className="measurement-warnings"><summary>Notas sobre estas mediciones ({record.features.analysis.warnings.length})</summary>{record.features.analysis.warnings.map((w, i) => <p key={i}>{w}</p>)}</details>}
    </section>
    <section className="panel context-panel"><div className="panel-heading"><div><span className="eyebrow">CONTEXTO Y PROCEDENCIA</span><h3>Cada muestra tiene una historia.</h3></div><span className="pill">Etiquetado humano</span></div><div className="two-fields"><label className="field">Sinopsis del estudiante<textarea rows={2} value={record.synopsis} placeholder="Intención y concepto de la pieza…" onChange={e => onChange({ synopsis: e.target.value })} /></label><label className="field">Objetivo del ejercicio<textarea rows={2} value={record.context} placeholder="Herramientas y objetivos que vas a evaluar…" onChange={e => onChange({ context: e.target.value })} /></label></div><div className="two-fields"><label className="field">Grupo de grabación de origen<input value={record.sourceGroup} placeholder="Ej.: campana-estudio-01" maxLength={200} onChange={e => onChange({ sourceGroup: e.target.value })} /><small>Usa el mismo grupo para el original y todas sus versiones procesadas.</small></label><label className="field">Comparar con una fuente de la biblioteca<select value={referenceId} onChange={e => onReference(e.target.value)}><option value="">Seleccionar original…</option>{records.filter(r => r.id !== record.id).map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><small>La comparación ayuda a verificar procesos que no se pueden deducir de una mezcla final.</small></label></div>{reference && <div className="reference-player"><div><b>Fuente: {reference.name}</b><p>Duración relativa: {(record.features.format.duration / reference.features.format.duration).toFixed(2)}× · diferencia de centroide: {Math.round(record.features.spectrum.centroidHz - reference.features.spectrum.centroidHz)} Hz. Son diferencias medidas, no pruebas de un efecto.</p></div>{referenceUrl ? <audio controls src={referenceUrl} aria-label="Reproducir fuente de referencia" /> : <p className="muted">Audio de referencia no disponible localmente.</p>}</div>}</section>
    <ReviewPanel record={record} onChange={onChange} />
    <section className="panel advice-panel"><div className="panel-heading"><div><span className="eyebrow">UNA SEGUNDA OPINIÓN</span><h3>La ayuda es opcional. El criterio, tuyo.</h3></div><button className="button secondary" aria-expanded={advice} onClick={() => setAdvice(!advice)}>{advice ? 'Ocultar asistentes' : 'Ver asistentes'}</button></div><p className="muted text-small">Consulta tu modelo local o un proveedor externo. Sus sugerencias se muestran aparte y no cambian la nota ni las etiquetas.</p>{advice && <Suspense fallback={<p>Cargando asistentes…</p>}><ModelAdvice record={record} analyzed={analyzed} model={model} onChange={onChange} /></Suspense>}</section>
  </div>;
}
