import { useRef, useState } from 'react';
import { ArrowUpRight, Download, FileAudio, Search, Trash2, Upload } from 'lucide-react';
import { calculateReview, labelProgress, type ReviewRecord } from '../../services/review';
import { downloadFile, exportCsv, exportDataset } from '../../services/library';
import UploadArea from './UploadArea';
import type { DemoId } from '../../services/audio/demos';
interface Props { records: ReviewRecord[]; busy: boolean; onSelect: (r: ReviewRecord) => void; onRemove: (r: ReviewRecord) => void; onFiles: (files: File[]) => void; onDemo: (id: DemoId) => void; onImport: (file: File) => void }
export default function LibraryView({ records, busy, onSelect, onRemove, onFiles, onDemo, onImport }: Props) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [deleteId, setDeleteId] = useState(''); const input = useRef<HTMLInputElement>(null);
  const visible = records.filter(r => `${r.name} ${r.sourceGroup}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || filter === 'real' && r.origin === 'real' || filter === 'pending' && calculateReview(r).pending.length > 0));
  return <div><div className="page-title"><span className="eyebrow">TU COLECCIÓN DE TRABAJO</span><h2>El conocimiento empieza<br />por una buena <em>muestra.</em></h2><p>Audios, mediciones y decisiones. Guardados en este navegador.</p></div><div className="library-tools"><label className="search-field"><Search size={17} /><input aria-label="Buscar muestras" placeholder="Buscar por archivo o grupo…" value={query} onChange={e => setQuery(e.target.value)} /></label><select aria-label="Filtrar muestras" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Todas las muestras</option><option value="real">Solo muestras reales</option><option value="pending">Pendientes de revisión</option></select><div className="toolbar"><button className="button secondary" onClick={() => input.current?.click()} disabled={busy}><Upload size={15} /> Importar JSON</button><button className="button secondary" disabled={!records.length} onClick={() => downloadFile(exportDataset(records), 'sonora-coleccion.json')}><Download size={15} /> Exportar JSON</button><button className="text-button" disabled={!records.length} onClick={() => downloadFile(exportCsv(records), 'sonora-muestras.csv', 'text/csv;charset=utf-8')}>CSV</button></div><input ref={input} className="visually-hidden" type="file" accept="application/json,.json" aria-label="Importar colección JSON" onChange={e => { if (e.target.files?.[0]) onImport(e.target.files[0]); e.target.value = ''; }} /></div>
    <div className="library-table-wrap"><table className="library-table"><thead><tr><th>Muestra</th><th>Origen</th><th>Revisión</th><th>Nota</th><th><span className="visually-hidden">Acciones</span></th></tr></thead><tbody>{visible.map(r => { const score = calculateReview(r); return <tr key={r.id}><td><button className="file-link" disabled={busy} onClick={() => onSelect(r)}><span className="file-icon"><FileAudio size={20} /></span><span><b>{r.name}</b><small>{r.features.format.duration.toFixed(0)} s · {(r.features.format.sampleRate / 1000).toFixed(1)} kHz {r.origin === 'synthetic' && '· DEMO'}</small></span><ArrowUpRight size={15} /></button></td><td>{r.sourceGroup || <span className="muted">Sin asignar</span>}</td><td><span className={`pill ${labelProgress(r) === 5 ? 'positive' : ''}`}>{labelProgress(r)} / 5 etiquetas</span></td><td className="mono">{score.final === null ? 'Pendiente' : `${score.final} / 30`}</td><td>{deleteId === r.id ? <span className="delete-confirm"><button onClick={() => { onRemove(r); setDeleteId(''); }}>Eliminar</button><button onClick={() => setDeleteId('')}>Cancelar</button></span> : <button className="icon-button" disabled={busy} aria-label={`Eliminar ${r.name}`} onClick={() => setDeleteId(r.id)}><Trash2 size={15} /></button>}</td></tr>; })}</tbody></table>{!visible.length && <div className="empty-table"><FileAudio size={30} /><h3>{records.length ? 'No hay coincidencias.' : 'Tu biblioteca está lista para empezar.'}</h3><p>{records.length ? 'Prueba otra búsqueda o filtro.' : 'Añade tus audios o abre un ejemplo desde el laboratorio.'}</p></div>}</div><p className="library-footnote">La exportación JSON incluye métricas y etiquetas, sin audio. Conserva tus archivos originales. Las copias de audio locales dependen del almacenamiento de este navegador.</p><UploadArea compact busy={busy} onFiles={onFiles} onDemo={onDemo} /></div>;
}
