import { Check, ClipboardCheck, RotateCcw } from 'lucide-react';
import { calculateReview, EFFECTS, type ReviewRecord, type ReviewLabel } from '../../services/review';

interface Props { record: ReviewRecord; onChange: (patch: Partial<ReviewRecord>) => void }
const labelOptions: { value: ReviewLabel; label: string }[] = [{ value: 'unknown', label: 'Pendiente' }, { value: 'present', label: 'Presente' }, { value: 'absent', label: 'Ausente' }];

export default function ReviewPanel({ record, onChange }: Props) {
  const score = calculateReview(record);
  return <div className="review-layout">
    <section className="panel human-review"><div className="panel-heading"><div><span className="eyebrow">CRITERIO DEL PROFESOR</span><h3>De la escucha a la evidencia.</h3></div><ClipboardCheck size={22} /></div><p className="muted text-small">Confirma cada herramienta. Una detección pendiente mantiene la nota abierta.</p>
      <div className="effect-list">{EFFECTS.map(effect => <div className="effect-row" key={effect.id}>
        <div className="effect-heading"><h4>{effect.label}{effect.id === 'loops' && <small>opcional</small>}</h4><div className="segmented" role="group" aria-label={`Revisión de ${effect.label}`}>{labelOptions.map(option => <button key={option.value} aria-pressed={record.labels[effect.id] === option.value} className={record.labels[effect.id] === option.value ? `selected ${option.value}` : ''} onClick={() => onChange({ labels: { ...record.labels, [effect.id]: option.value } })}>{option.value === 'present' && <Check size={12} />}{option.label}</button>)}</div></div>
        <p>{effect.hint}</p><label className="evidence-input"><span>Evidencia</span><input aria-label={`Evidencia de ${effect.label}`} placeholder="Ej.: 0:12–0:18 · comparación con la fuente" value={record.evidence[effect.id]} onChange={e => onChange({ evidence: { ...record.evidence, [effect.id]: e.target.value } })} /></label>
      </div>)}</div>
      <div className="two-fields"><label>Sobreprocesamiento<select aria-label="Sobreprocesamiento" value={record.overprocessing} onChange={e => onChange({ overprocessing: e.target.value as ReviewRecord['overprocessing'] })}><option value="unknown">Pendiente de revisión</option><option value="none">No se aprecia</option><option>Leve</option><option>Moderado</option><option>Severo</option></select></label><label>Efectos extra<select aria-label="Efectos extra" value={record.extra} onChange={e => onChange({ extra: e.target.value as ReviewLabel })}><option value="unknown">Pendiente de revisión</option><option value="present">Confirmados (+0,5)</option><option value="absent">Sin efectos extra</option></select></label></div>
      <label className="field">Feedback para el estudiante<textarea rows={3} placeholder="Qué funciona, qué revisar y en qué momento…" value={record.notes} onChange={e => onChange({ notes: e.target.value })} /></label>
    </section>
    <aside className="score-panel"><span className="eyebrow">EVALUACIÓN / 30 PUNTOS</span><div className="score-display" data-testid="final-score">{score.final === null ? <span className="pending-score">En revisión</span> : <><strong>{score.final.toLocaleString('es', { maximumFractionDigits: 2 })}</strong><span>/ 30</span></>}</div><p>{score.manual ? 'Nota ajustada por el profesor.' : score.pending.length ? `${score.pending.length} decisiones pendientes. Rango posible: ${score.minimum}–${score.maximum}.` : 'Revisión completa. Calculada con la rúbrica.'}</p>
      <div className="score-breakdown">{[{ label: 'Formal', value: score.formal.total, max: 5 }, { label: 'Técnica', value: score.technical.total, max: 12.5 }, { label: 'Creatividad', value: score.creative.total, max: 12.5 }].map(row => <div key={row.label}><span>{row.label}</span><b>{row.label === 'Creatividad' && score.pending.length ? `${score.creative.minimum}–${row.value}` : row.value}<small> / {row.max}</small></b><div><i style={{ width: `${row.value / row.max * 100}%` }} /></div></div>)}<div className="bonus-row"><span>Extra</span><b>{record.extra === 'unknown' ? 'Pendiente' : `+${score.bonus}`}</b></div></div>
      <details className="score-details"><summary>Ver desglose de criterios</summary>{[...score.formal.lines, ...score.technical.lines, ...score.creative.lines].map((line, i) => <div key={i}><b>{line.criterio}</b><span>{'pending' in line && line.pending ? 'Pendiente' : `${line.puntos > 0 ? '+' : ''}${line.puntos}`}</span><p>{line.detalle}</p></div>)}</details>
      <label className="field">Ajustar nota manualmente<input type="number" min={0} max={30.5} step={0.1} value={record.manualScore ?? ''} placeholder="Sin ajuste" onChange={e => { if (e.target.value === '') onChange({ manualScore: null }); else if (e.target.validity.valid) onChange({ manualScore: Number(e.target.value) }); }} /></label>{score.manual && <button className="text-button" onClick={() => onChange({ manualScore: null })}><RotateCcw size={13} /> Volver a la nota calculada</button>}
      <div className="score-note">La rúbrica admite hasta 0,5 puntos extra. Las sugerencias de modelos no cambian tus decisiones.</div>
    </aside>
  </div>;
}
