import { Check, ClipboardCheck, PenLine, RotateCcw } from 'lucide-react';
import { draftFeedback } from '../../services/feedback';
import { calculateReview, EFFECTS, type ReviewRecord, type ReviewLabel } from '../../services/review';
import type { RubricConfig } from '../../services/scoring/rubric';
import type { EngineSettings } from '../../services/engines';

interface Props { record: ReviewRecord; rubric: RubricConfig; engines?: EngineSettings; onChange: (patch: Partial<ReviewRecord>) => void }
const labelOptions: { value: ReviewLabel; label: string }[] = [{ value: 'unknown', label: 'Pendiente' }, { value: 'present', label: 'Presente' }, { value: 'absent', label: 'Ausente' }];

export default function ReviewPanel({ record, rubric, engines, onChange }: Props) {
  const ai = record.ai;
  const score = calculateReview(record, rubric);
  const required = new Set(rubric.creative.requiredTools);
  const maxManual = rubric.totalPoints + rubric.bonus.points;
  return <div className="review-layout">
    <section className="panel human-review"><div className="panel-heading"><div><span className="eyebrow">CRITERIO DEL PROFESOR</span><h3>De la escucha a la evidencia.</h3></div><ClipboardCheck size={22} /></div><p className="muted text-small">Confirma cada herramienta. Una detección pendiente mantiene la nota abierta.</p>
      <div className="effect-list">{EFFECTS.map(effect => <div className="effect-row" key={effect.id}>
        <div className="effect-heading"><h4>{effect.label}{!required.has(effect.id) && <small>opcional</small>}</h4><div className="segmented" role="group" aria-label={`Revisión de ${effect.label}`}>{labelOptions.map(option => <button key={option.value} aria-pressed={record.labels[effect.id] === option.value} className={record.labels[effect.id] === option.value ? `selected ${option.value}` : ''} onClick={() => onChange({ labels: { ...record.labels, [effect.id]: option.value } })}>{option.value === 'present' && <Check size={12} />}{option.label}</button>)}</div></div>
        <p>{effect.hint}</p><label className="evidence-input"><span>Evidencia</span><input aria-label={`Evidencia de ${effect.label}`} placeholder="Ej.: 0:12–0:18 · comparación con la fuente" value={record.evidence[effect.id]} onChange={e => onChange({ evidence: { ...record.evidence, [effect.id]: e.target.value } })} /></label>
      </div>)}</div>
      <div className="two-fields"><label>Sobreprocesamiento<select aria-label="Sobreprocesamiento" value={record.overprocessing} onChange={e => onChange({ overprocessing: e.target.value as ReviewRecord['overprocessing'] })}><option value="unknown">Pendiente de revisión</option><option value="none">No se aprecia</option><option>Leve</option><option>Moderado</option><option>Severo</option></select></label><label>Efectos extra<select aria-label="Efectos extra" value={record.extra} onChange={e => onChange({ extra: e.target.value as ReviewLabel })}><option value="unknown">Pendiente de revisión</option><option value="present">Confirmados (+{rubric.bonus.points.toLocaleString('es')})</option><option value="absent">Sin efectos extra</option></select></label></div>
      <label className="field">Feedback para el estudiante<textarea rows={3} placeholder="Qué funciona, qué revisar y en qué momento…" value={record.notes} onChange={e => onChange({ notes: e.target.value })} /></label>
      <div className="draft-row"><button type="button" className="button secondary" onClick={() => { const d = draftFeedback(record, rubric); onChange({ notes: record.notes.trim() ? `${record.notes.trim()}\n\n${d.text}` : d.text }); }}><PenLine size={14} /> Redactar borrador</button><small className="muted text-small">Se redacta aquí, sin IA externa, a partir de las mediciones y de tus anotaciones. Edítalo antes de publicar.</small></div>
    </section>
    <aside className="score-panel"><span className="eyebrow">EVALUACIÓN / {score.maxTotal.toLocaleString('es')} PUNTOS</span><div className="score-display" data-testid="final-score">{score.final === null ? <span className="pending-score">En revisión</span> : <><strong>{score.final.toLocaleString('es', { maximumFractionDigits: 2 })}</strong><span>/ {score.maxTotal.toLocaleString('es')}</span></>}</div><p>{score.manual ? 'Nota ajustada por el profesor.' : score.pending.length ? `${score.pending.length} decisiones pendientes. Rango posible: ${score.minimum}–${score.maximum}.` : 'Revisión completa. Calculada con la rúbrica.'}</p>
      <div className="score-breakdown">{[{ label: 'Formal', value: score.formal.total, max: score.formalMax }, { label: 'Técnica', value: score.technical.total, max: score.technicalMax }, { label: 'Creatividad', value: score.creative.total, max: score.creative.max }].map(row => <div key={row.label}><span>{row.label}</span><b>{row.label === 'Creatividad' && score.pending.length ? `${score.creative.minimum}–${row.value}` : row.value}<small> / {row.max}</small></b><div><i style={{ width: `${row.max ? row.value / row.max * 100 : 0}%` }} /></div></div>)}<div className="bonus-row"><span>Extra</span><b>{record.extra === 'unknown' ? 'Pendiente' : `+${score.bonus}`}</b></div></div>
      <details className="score-details"><summary>Ver desglose de criterios</summary>{[...score.formal.lines, ...score.technical.lines, ...score.creative.lines].map((line, i) => <div key={i}><b>{line.criterio}</b><span>{'pending' in line && line.pending ? 'Pendiente' : `${line.puntos > 0 ? '+' : ''}${line.puntos}`}</span><p>{line.detalle}</p></div>)}</details>
      <label className="field">Ajustar nota manualmente<input type="number" min={0} max={maxManual} step={0.1} value={record.manualScore ?? ''} placeholder="Sin ajuste" onChange={e => { if (e.target.value === '') onChange({ manualScore: null }); else if (e.target.validity.valid) onChange({ manualScore: Number(e.target.value) }); }} /></label>{score.manual && <button className="text-button" onClick={() => onChange({ manualScore: null })}><RotateCcw size={13} /> Volver a la nota calculada</button>}
      {ai && <div className="used-opinion"><span className="eyebrow">SEGUNDA OPINIÓN USADA</span><div><span>Motor</span><b>{ai.meta.modelLabel}</b></div><div><span>Ejecuciones · acuerdo</span><b>{ai.meta.runs} · {ai.meta.agreement === null ? 'n/a' : `${Math.round(ai.meta.agreement * 100)} %`}</b></div><div><span>Coste orientativo</span><b>{ai.meta.estimatedCostUsd.toFixed(4)} $</b></div></div>}
      {!ai && engines && engines.engine !== 'local' && <div className="used-opinion"><span className="eyebrow">SEGUNDA OPINIÓN</span><div><span>Motor elegido</span><b>{engines.models[engines.engine]}</b></div><div><span>Estado</span><b>Sin consultar</b></div></div>}
      {record.student && <div className={`publish-state ${record.published ? 'on' : ''}`}>{record.published ? 'Nota y feedback publicados: el estudiante ya los ve.' : 'Nota sin publicar: el estudiante solo ve las mediciones.'}</div>}
      <div className="score-note">La rúbrica admite hasta {rubric.bonus.points.toLocaleString('es')} puntos extra. Las sugerencias de modelos no cambian tus decisiones.</div>
    </aside>
  </div>;
}
