import { ArrowLeft, BookOpen, CircleHelp, GraduationCap, UserRound } from 'lucide-react';

export type GuideRole = 'teacher' | 'student';
interface Props { role: GuideRole; onRole?: (role: GuideRole) => void; onBack?: () => void; backLabel?: string }

/** Un paso de la guía. Las imágenes viven en public/guia y las genera `npm run guia:capturas`; el texto cita sus números. */
export interface Step { title: string; text: string; tip?: string; images?: string[] }

/** URL de una captura respetando la ruta base del despliegue (GitHub Pages sirve bajo /sonora/). */
export const guideUrl = (file: string, base = (import.meta as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/') => `${base.endsWith('/') ? base : `${base}/`}guia/${file}`;

export const TEACHER_STEPS: Step[] = [
  { title: 'Entra con el PIN de profesor', text: 'En la pantalla de entrada escribe el PIN acordado (1) y pulsa «Entrar como profesor» (2). La sesión se guarda en este navegador hasta que pulses «Salir».', tip: 'En un equipo compartido pulsa «Salir» al terminar: si no, quien venga después entra como profesor.', images: ['profesor-01-entrada.png'] },
  { title: 'Sube o recibe audios', text: 'En Laboratorio arrastra archivos WAV, AIFF o FLAC (1), uno o varios. Las demos (2) son ejemplos sintéticos para practicar: se identifican como tales y nunca entrenan el modelo. Las entregas de los estudiantes aparecen en Biblioteca con su nombre y fecha. Nada sale del navegador.', images: ['profesor-02-laboratorio.png'] },
  { title: 'Lee las mediciones', text: 'Cada archivo muestra sonoridad (LUFS), pico real, saturación, clics, silencios y espectro (1): medidas reales según ITU-R BS.1770 que puntúan solas la parte técnica. La forma de onda (2) lleva pintado cada clic, saturación o silencio; y la lista de evidencias reúne todo con su momento y su fuente: medido, anotado por ti o sugerido por un modelo.', tip: 'Pulsa una marca de la onda o una fila de evidencias para escuchar justo ese momento.', images: ['profesor-03-mediciones.png', 'profesor-03b-evidencias.png'] },
  { title: 'Confirma cada herramienta', text: 'En «Criterio del profesor» decide presente, ausente o pendiente para pitch shift, time stretch, reversa, filtros y loops (1), y escribe la evidencia. La nota (2) se calcula con la rúbrica al instante; mientras quede algo pendiente, la nota sigue abierta y se muestra el rango posible.', tip: 'Con la fuente original en la biblioteca, elige una referencia en el panel de contexto para escuchar A/B.', images: ['profesor-04-revisar.png'] },
  { title: 'Marca dónde ocurre', text: 'Sube el zoom (1) para trabajar con precisión. Elige la herramienta y activa «Marcar» (2): arrastrar sobre la onda crea una marca de ese tramo; si prefieres no usar el ratón, «Marcar desde el tiempo actual» crea una desde el cursor. Cada marca (3) tiene inicio, fin y comentario, y encabeza la lista de evidencias.', tip: 'La primera marca de una herramienta pendiente la propone como «presente»; borrarla no cambia tu decisión.', images: ['profesor-05-marcar.png'] },
  { title: 'Pide una segunda opinión', text: 'En Motores de IA eliges el modelo local (gratis, en tu equipo) o un proveedor externo con tu clave. Las sugerencias nunca cambian etiquetas ni notas: solo señalan dónde mirar.' },
  { title: 'Redacta el feedback y publica', text: '«Redactar borrador» convierte mediciones y anotaciones en un texto editable (2). Con la revisión completa, «Publicar al estudiante» le muestra nota y comentarios y congela esa nota (1): si después cambias la rúbrica o una etiqueta, tu cálculo cambia pero lo publicado no, y verás la diferencia con «Volver a publicar».', images: ['profesor-07-publicar.png', 'profesor-07b-nota.png'] },
  { title: 'Ajusta la rúbrica', text: 'En Rúbrica cambias puntos, penalizaciones y herramientas obligatorias. Escribe el formato del nombre de archivo como en el enunciado (1), por ejemplo «{estudiante}_ejercicio{numero}», y pruébalo con un nombre real (2) antes de guardar (3). El estudiante verá el formato, con un ejemplo hecho con su nombre, antes de subir.', images: ['profesor-08-rubrica.png'] },
  { title: 'Entrena el modelo local', text: 'Modelo local (1) te dice cuántas muestras reales y orígenes tienes y qué herramientas cumplen el mínimo (3). Antes del primer entrenamiento, congela el conjunto de evaluación (2): aparta orígenes enteros que nunca entrenan y sobre los que se mide cada modelo. Esa columna «Congelado» es la única cifra comparable entre entrenamientos; el historial la guarda.', tip: 'En Muestras puedes importar el corpus de ejemplo (900 variantes con etiqueta exacta) y cargar el modelo ya entrenado para empezar.', images: ['profesor-09-modelo.png', 'profesor-09b-validacion.png'] },
  { title: 'Exporta y comparte', text: 'Desde Biblioteca (1) buscas, filtras, importas y exportas: CSV para tu hoja de notas (con la nota viva y la publicada) o JSON para llevar la colección a otro equipo o contribuirla al repositorio. La tabla (2) muestra el estado de cada muestra.', images: ['profesor-10-biblioteca.png'] },
];
export const STUDENT_STEPS: Step[] = [
  { title: 'Entra con tu nombre', text: 'Escribe tu nombre completo (1) tal y como quieres que lo vea tu profesor y pulsa «Entrar como estudiante» (2). Con ese nombre se identifican tus entregas; usa siempre el mismo.', images: ['estudiante-01-entrada.png'] },
  { title: 'Prepara el archivo', text: 'Exporta tu proyecto en WAV, AIFF o FLAC (no MP3), hasta 200 MB (2). Si tu profesor ha fijado un formato de nombre, lo verás antes de subir con un ejemplo hecho con tu nombre (1): síguelo tal cual, porque el nombre puntúa.', tip: 'Deja al menos 1 dB de margen por debajo de 0 dBFS y evita cortes sin fundido: la app los detecta.', images: ['estudiante-02-preparar.png'] },
  { title: 'Entrega', text: 'En Entregar arrastra el archivo o pulsa para elegirlo. Queda registrado a tu nombre con fecha (1) y se analiza en tu navegador (2); el audio se guarda en este equipo y el profesor lo verá cuando lo abra aquí.', images: ['estudiante-03-entregar.png'] },
  { title: 'Escribe la sinopsis', text: 'Cuenta qué querías conseguir y qué procesos usaste, con tiempos (1): «reversa en 0:12–0:18». La sinopsis puntúa y ayuda al profesor a encontrar cada proceso.', images: ['estudiante-04-sinopsis.png'] },
  { title: 'Mira las mediciones', text: 'Verás nivel, pico real, saturación y clics con el momento exacto en la onda (1) y en la lista de evidencias (2). Si algo sale mal puedes corregir el proyecto y volver a entregar antes de que lo revisen.', images: ['estudiante-05-mediciones.png'] },
  { title: 'Lectura orientativa', text: 'Si tu profesor la ha activado, puedes pedir una lectura de un modelo de IA: qué se oye, fortalezas y mejoras. No es una nota ni sustituye la revisión del profesor.' },
  { title: 'Consulta tu calificación', text: 'En Mis entregas aparecerá «Calificado» cuando el profesor publique (1). Al abrir la entrega verás la nota, el desglose por criterios, las marcas que dejó sobre tu audio y sus comentarios (2). Esa nota no cambia aunque el profesor ajuste la rúbrica después; si vuelve a publicar, verás la nueva.', images: ['estudiante-07-entregas.png', 'estudiante-07-calificacion.png'] },
];

export default function GuideView({ role, onRole, onBack, backLabel = 'Volver' }: Props) {
  const steps = role === 'teacher' ? TEACHER_STEPS : STUDENT_STEPS;
  return <div className="guide-view">
    {onBack && <button type="button" className="text-button guide-back" onClick={onBack}><ArrowLeft size={14} /> {backLabel}</button>}
    <div className="page-title"><span className="eyebrow">TUTORIAL DE USO</span><h2>{role === 'teacher' ? <>Del archivo a la nota,<br /><em>paso a paso.</em></> : <>Entregar bien<br />es <em>fácil.</em></>}</h2><p>{role === 'teacher' ? 'Todo ocurre en tu navegador. Esta guía recorre el flujo completo: recibir, medir, marcar, confirmar, publicar y entrenar. Los números de cada imagen se citan en el texto.' : 'Sigue estos pasos y tu profesor recibirá tu proyecto con las mediciones y tu sinopsis. Los números de cada imagen se citan en el texto.'}</p></div>
    {onRole && <div className="segmented guide-roles" role="group" aria-label="Guía para"><button type="button" aria-pressed={role === 'teacher'} className={role === 'teacher' ? 'selected' : ''} onClick={() => onRole('teacher')}><GraduationCap size={13} /> Profesor</button><button type="button" aria-pressed={role === 'student'} className={role === 'student' ? 'selected' : ''} onClick={() => onRole('student')}><UserRound size={13} /> Estudiante</button></div>}
    <ol className="guide-steps">
      {steps.map((s, i) => <li className="guide-step guide-card" key={s.title}><span>{String(i + 1).padStart(2, '0')}</span><div><h4>{s.title}</h4><p>{s.text}</p>{s.tip && <p className="guide-tip"><CircleHelp size={13} /> {s.tip}</p>}
        {s.images?.map(file => <figure className="guide-figure" key={file}><a href={guideUrl(file)} target="_blank" rel="noreferrer" aria-label={`Abrir a tamaño completo: ${s.title}`}><img src={guideUrl(file)} alt={`Captura de pantalla: ${s.title}`} loading="lazy" /></a></figure>)}
      </div></li>)}
    </ol>
    <div className="method-note"><BookOpen size={20} /><p>{role === 'teacher' ? <><b>Qué mide y qué no.</b> Las mediciones técnicas son exactas y reproducibles. La detección de procesos creativos (pitch, stretch, reversa, filtros, loops) es siempre una sugerencia que confirmas tú: el modelo local se abstiene cuando no está seguro y los proveedores externos opinan, no deciden.</> : <><b>Sobre tu privacidad.</b> Tu audio no se sube a ningún servidor: se analiza y se guarda en el navegador del equipo donde entregas. Si pides una lectura de IA externa, se envían las mediciones y tu sinopsis, no el audio.</>}</p></div>
  </div>;
}
